// <auto-generated />
namespace MU_Clubs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class exit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exit));
        
        string IMigrationMetadata.Id
        {
            get { return "201905050845516_exit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
